plugins {
    id 'com.android.application'
}

android {
    namespace 'design.archdesign.wheel'
    compileSdk 34

    defaultConfig {
        applicationId "design.archdesign.wheel"
        minSdk 26
        targetSdk 34
        versionCode((System.getenv("GITHUB_RUN_NUMBER") ?: "1").toInteger())
        versionName "1." + (System.getenv("GITHUB_RUN_NUMBER") ?: "0")
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
